// GENERATED by scripts/generate-expected-tables.js — do not edit by hand.
// Run the script after adding a table to supabase/types.ts; CI fails if this
// file drifts from types.ts + supabase/migrations.
//
// Migrations are applied to the live tenant MANUALLY. This list is what lets
// /api/v1/system/persistence say WHICH migration has not been run yet, instead
// of a page quietly rendering an empty list for a table that does not exist.

export interface ExpectedTable {
  /** Table name as PostgREST sees it. */
  table: string;
  /** The migration file that creates it — the one to run if it is missing. */
  migration: string | null;
}

export const EXPECTED_TABLES: ExpectedTable[] = [
  { table: "annex_a_evidence_queue", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "audit_log", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "behaviour_support_plans", migration: "20260815090000_persist_behaviour_support_plans.sql" },
  { table: "building_checks", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "buildings", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "candidate_checks", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "candidate_profiles", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "candidate_references", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "cara_interactions", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "care_event_audit_log", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "care_event_jobs", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "care_event_routes", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "care_events", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "care_forms", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "child_daily_summaries", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "chronology_entries", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "cs_communication_drafts", migration: "20260816210000_persist_communication_drafts.sql" },
  { table: "daily_log_entries", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "document_read_receipts", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "documents", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "expenses", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "filing_cabinet_items", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "generic_records", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "handovers", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "incidents", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "leave_requests", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "maintenance_items", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "management_oversight_tasks", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "medication_administrations", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "medications", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "missing_episodes", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "notifications", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "qa_audits", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "reg40_tasks", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "reg45_evidence_queue", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "saved_time_metrics", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "shifts", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "staff_members", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "supervisions", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "tasks", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "time_saved_entries", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "training_records", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "vacancies", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "vehicle_checks", migration: "20260722120000_persist_typed_tables.sql" },
  { table: "vehicles", migration: "00000000000000_lean_live_baseline.sql" },
  { table: "young_people", migration: "00000000000000_lean_live_baseline.sql" },
];
