export {
  generateComplaintsAdvocacyAccessIntelligence,
  evaluateComplaintsHandling,
  evaluateAdvocacyAccess,
  evaluateResolutionQuality,
  evaluateStaffComplaintsReadiness,
  buildChildComplaintsSummaries,
  pct,
  getRating,
  getComplaintTypeLabel,
  getComplaintStatusLabel,
  getResolutionOutcomeLabel,
  getAdvocacyTypeLabel,
  getSatisfactionLevelLabel,
  getRatingLabel,
} from "./complaints-advocacy-access-engine";

export type {
  ComplaintType,
  ComplaintStatus,
  ResolutionOutcome,
  AdvocacyType,
  SatisfactionLevel,
  Rating,
  ComplaintRecord,
  AdvocacyRecord,
  ComplaintsPolicy,
  StaffComplaintsTraining,
  ComplaintsHandlingResult,
  AdvocacyAccessResult,
  ResolutionQualityResult,
  StaffComplaintsReadinessResult,
  ChildComplaintsSummary,
  ComplaintsAdvocacyAccessIntelligence,
} from "./complaints-advocacy-access-engine";
